# frozen_string_literal: true
module Graph
  module Types
    module Mongodb
      class Explain < Types::BaseObject
        description 'MongoDB Query Explain'

        field :id, ID, null: false, description: 'Log primary key'
        field :collection, String, null: false, description: 'Collection name'
        field :source_name, String, null: false, description: 'Query originating source'
        field :command, String, null: false, description: 'The command performed'
        field :collscan, Boolean, null: true, description: 'A COLLSCAN flag'
        field :winning_plan, String, null: false, description: 'MongoDB winning plan'
        field :winning_plan, String, null: false, description: 'MongoDB winning plan'
        field :winning_plan_raw, String, null: false, description: 'MongoDB winning plan raw json'
        field :used_indexes, String, null: false, description: 'MongoDB indexes used if any'
        field :duration, Float, null: false, description: 'Query duration in seconds'
        field :documents_returned, Integer, null: true, description: 'Total number of MongoDB documents returned by the query'
        field :documents_examined, Integer, null: true, description: 'Total number of MongoDB documents examined by the query'
        field :keys_examined, Integer, null: true, description: 'Total number of MongoDB keys examined by the query'
        field :rejected_plans, Integer, null: true, description: 'Total number of rejected plans'
        field :stages_count, Integer, null: true, description: 'Total number of rejected plans'
        field :session_id, String, null: false, description: 'A unique id identifying a session during which queries are logged.'
        field :lsid, String, null: false, description: 'Unique id generated by MonoDB server'
        field :treeviz, String, null: true, description: "MongoDB's explain as JSON"
        field :log, Graph::Types::Mongodb::Log, null: false, description: 'Query log'
        field :stacktrace, Graph::Types::Mongodb::Stacktrace, null: false, description: 'Rails Stacktrace'
        field :controller, Graph::Types::Mongodb::Controller, null: true, description: 'Rails controller'

        timestamps(self)
      end
    end
  end
end
